# Use an official Maven image with JDK 17
FROM maven:3.8.5-openjdk-17

# Set the working directory inside the container
WORKDIR /app

# Copy the pom.xml file and download dependencies
COPY pom.xml .
RUN mvn dependency:go-offline

COPY src ./src

# Default command to run the application
CMD ["mvn", "spring-boot:run"]
