steps:
  # Step 1: Pull code from GitHub
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', '--depth=1', 'https://github.com/ayushi250317/k8s-assignment.git', '.']
    dir: '/k8s/InputValidator/InputValidator'  # Specify the directory where cloudbuild.yaml is located
    
  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/app1:$COMMIT_SHA', '.']
   ## dir: 'build-config'  # Specify the directory where cloudbuild.yaml is located
    
  # Step 3: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/app1:$COMMIT_SHA']
##    dir: 'build-config'  # Specify the directory where cloudbuild.yaml is located

images:
  # Specify the image to be pushed to Artifact Registry
  - 'gcr.io/$PROJECT_ID/app1:$COMMIT_SHA'
