steps:
  # Step 1: Pull code from GitHub
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git clone --depth=1 https://github.com/ayushi250317/k8s-assignment.git /workspace
        cp -r /workspace/k8s/InputValidator/InputValidator/* .

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/app1:$COMMIT_SHA'
      - '.'
    dir: '/workspace/k8s/InputValidator/InputValidator'  # Specify the directory where Dockerfile is located

  # Step 3: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/app1:$COMMIT_SHA'

images:
  # Specify the image to be pushed to Artifact Registry
  - 'gcr.io/$PROJECT_ID/app1:$COMMIT_SHA'
